# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    services:
      grumble:
        image: avhost/docker-murmur
        ports:
          - 64738:64738
          - 64738:64738/udp
    
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install Dependencies
      run: yarn --frozen-lockfile
    - name: Lint
      continue-on-error: true
      run: yarn lint
    - name: Install ffmpeg
      run: |
        sudo apt update
        sudo apt install ffmpeg
    - name: Test
      run: yarn test
      env:
        MUMBLE_URL: 127.0.0.1
    
